CREATE TABLE BANK_ACCOUNTS (
    ACCOUNT_ID NUMBER PRIMARY KEY,
    ACCOUNT_HOLDER VARCHAR2(100),
    BALANCE NUMBER(10,2)
);

INSERT INTO BANK_ACCOUNTS VALUES (101, 'Alice', 5000);
INSERT INTO BANK_ACCOUNTS VALUES (102, 'Bob', 3000);
COMMIT;


CREATE OR REPLACE FUNCTION WITHDRAW_FUNDS(
    P_ACCOUNT_ID IN NUMBER, 
    P_AMOUNT IN NUMBER
) RETURN VARCHAR2 IS
    V_BALANCE NUMBER(10,2);
BEGIN
    SELECT BALANCE INTO V_BALANCE 
    FROM BANK_ACCOUNTS 
    WHERE ACCOUNT_ID = P_ACCOUNT_ID;

    IF V_BALANCE >= P_AMOUNT THEN
        UPDATE BANK_ACCOUNTS 
        SET BALANCE = BALANCE - P_AMOUNT
        WHERE ACCOUNT_ID = P_ACCOUNT_ID;
        
        COMMIT; 
        RETURN 'Success: Amount Withdrawn';
    ELSE
        RETURN 'Error: Insufficient Funds';
    END IF;
    
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 'Error: Account Not Found';
    WHEN OTHERS THEN
        RETURN 'Error: Transaction Failed';
END WITHDRAW_FUNDS;
/


DECLARE
    V_RESULT VARCHAR2(50);
BEGIN
    V_RESULT := WITHDRAW_FUNDS(101, 2000);  
    DBMS_OUTPUT.PUT_LINE(V_RESULT);
END;
/
